### PR TITLE
Address AS-62: header link

### PR DESCRIPTION
**Pull request by CanOfBees**
**JIRA Ticket**: [AS-62](https://jirautk.atlassian.net/browse/AS-62)

# What does this Pull Request do?

This wraps the title/sub-title of the public UI in a link back to the main public UI.

# How should this be tested?

In your vagrant/docker environment, pull in these changes and restart the application. Once the UIs are available, reload  the public UI and clicking the title or sub-title links back to the main public UI.

### CODE REVIEW

**Review by markpbaggett — APPROVED** [review]
@CanOfBees, this looks good to me.  How many approvers do we need before merge? Who deploys?

**Comment by CanOfBees** [comment]
@markpbaggett thanks for the review. Maybe wait until Mat's had a chance to take a look? I'll merge and deploy after he approves, if that sounds okay.

**Review by mathewjordan — APPROVED** [review]
@CanOfBees This is good to go. Thanks.

**Comment by mathewjordan** [comment]
@CanOfBees Will you deploy when you have time? As it's _trivial_, can wait until Monday if necessary.

**Comment by CanOfBees** [comment]
@mathewjordan will deploy later tonight. Thanks for the review and merge.

**Pull request merged**
