### PR TITLE
Address Special Collections request modal instruction updates

### PR DESCRIPTION
**Pull request by mathewjordan**
# What does this Pull Request do?

Adds HTML formatted instructional text on the feedback modal per a Special Collections request. 

image

# What's new?

* Adds **note_additional** key and html formatted list items
* Renders list items within an unordered list element on the request form template
* Styles list and list items to fit with neatly in request form modal
* Updates placeholder text on textarea to point user to instructional text below

# How should this be tested?

From your local docker instance of **utk_archivesspace_docker**
* Update the `.env` file to `BRANCH=request-updates`
* `docker-compose up --build -d`
* _Wait..._
* Look at any collection item
* Click request
* HTML formatted text will render in the modal

# Additional Notes:
This may not be the _best_ way to handle this. I saw conflicting methods to safely output HTML and eventually landed on the method used in the a145b6c commit. The show.html.erb file does something similar when rendering the welcome message on the homepage and I gave it go. My struggle to get to this point is why there are so many commits.

Also, tagging @CanOfBees just so he's aware this is coming. Suppose we can deploy on Monday.

# Interested parties
@markpbaggett @CanOfBees

### CODE REVIEW

**Comment by markpbaggett** [comment]
@mathewjordan this looks good to me.  Let's talk about deploying this tomorrow morning.

**Comment by mathewjordan** [comment]
@markpbaggett The requested change has been addressed in  a00763c. Looks good from my local.

**Comment by markpbaggett** [comment]
> @markpbaggett The requested change has been addressed in [a00763c](https://github.com/utkdigitalinitiatives/utk-archivesspace-local/commit/a00763c7d4962bcefc568fd1148bb4649218d84a). Looks good from my local.

@mathewjordan this looks good.  Let's wait for feedback from Kris and Special Collections before we merge.

**Comment by CanOfBees** [comment]
@markpbaggett thanks for merging. Are there any other things we need to do before deploying these changes?

**Comment by markpbaggett** [comment]
Nope.  Checkout master and restart ArchivesSpace.

**Pull request merged**
