### PR TITLE
Add appropriate branding for SCOUT.

### PR DESCRIPTION
**Pull request by markpbaggett**
**JIRA Ticket**: [DI-1436](https://jirautk.atlassian.net/browse/DI-1436)

# What does this Pull Request do?

Changes the name branding to match the request in the ticket.

# How should this be tested?

I did it live.  Does it look okay?

### CODE REVIEW

**Review by CanOfBees — COMMENTED** [review]
@markpbaggett  I'm not sure if I'm following the ticket. Does it refer to *all* branding, or just the title for the Betsey Creekmore collection?

In any case, the title in `public/locales/en.yml` is definitely updated to match:
```
SCOUT
Special Collections Online at UT
```

**Review by pc37utn — APPROVED** [review]
the places mentioned in the ticket are showing up crrectly.

**Comment by markpbaggett** [comment]
@

> @markpbaggett I'm not sure if I'm following the ticket. Does it refer to _all_ branding, or just the title for the Betsey Creekmore collection?
> 
> In any case, the title in `public/locales/en.yml` is definitely updated to match:
> 
> ```
> SCOUT
> Special Collections Online at UT
> ```

The ticket asked for us to change the values on these two pages:

* https://scout.lib.utk.edu/repositories
* https://scout.lib.utk.edu/repositories/2

Do you see it anywhere else?

I updated those locales based on the description on the main page and thought it was a good idea to use locales rather than hardcoding in case this happens again.

Let me know if your question still is not answered or if I'm missing a value.

**Review by CanOfBees — APPROVED** [review]
@markpbaggett Thanks - I follow now. Sorry for the silly question. :+1:

**Pull request merged**
